/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appAppRouteImport } from './routes/(app)/_app'
import { Route as webWebRouteImport } from './routes/(web)/_web'
import { Route as webAboutRouteImport } from './routes/(web)/about'
import { Route as appAppDashboardRouteImport } from './routes/(app)/_app.dashboard'
import { Route as appAppSinistresRouteImport } from './routes/(app)/_app.sinistres'
import { Route as webWebIndexRouteImport } from './routes/(web)/_web.index'
import { Route as webDemoI18nRouteImport } from './routes/(web)/demo.i18n'
import { Route as webDemoPrismaRouteImport } from './routes/(web)/demo/prisma'
import { Route as webDemoStoreRouteImport } from './routes/(web)/demo/store'
import { Route as webDemoTableRouteImport } from './routes/(web)/demo/table'
import { Route as webDemoFormAddressRouteImport } from './routes/(web)/demo/form.address'
import { Route as webDemoFormSimpleRouteImport } from './routes/(web)/demo/form.simple'

const appAppRoute = appAppRouteImport.update({
  id: '/(app)/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const webWebRoute = webWebRouteImport.update({
  id: '/(web)/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const webAboutRoute = webAboutRouteImport.update({
  id: '/(web)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppDashboardRoute = appAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appAppRoute,
} as any)
const appAppSinistresRoute = appAppSinistresRouteImport.update({
  id: '/sinistres',
  path: '/sinistres',
  getParentRoute: () => appAppRoute,
} as any)
const webWebIndexRoute = webWebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => webWebRoute,
} as any)
const webDemoI18nRoute = webDemoI18nRouteImport.update({
  id: '/(web)/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const webDemoPrismaRoute = webDemoPrismaRouteImport.update({
  id: '/(web)/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const webDemoStoreRoute = webDemoStoreRouteImport.update({
  id: '/(web)/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const webDemoTableRoute = webDemoTableRouteImport.update({
  id: '/(web)/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const webDemoFormAddressRoute = webDemoFormAddressRouteImport.update({
  id: '/(web)/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const webDemoFormSimpleRoute = webDemoFormSimpleRouteImport.update({
  id: '/(web)/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof webAboutRoute
  '/dashboard': typeof appAppDashboardRoute
  '/sinistres': typeof appAppSinistresRoute
  '/demo/i18n': typeof webDemoI18nRoute
  '/demo/prisma': typeof webDemoPrismaRoute
  '/demo/store': typeof webDemoStoreRoute
  '/demo/table': typeof webDemoTableRoute
  '/': typeof webWebIndexRoute
  '/demo/form/address': typeof webDemoFormAddressRoute
  '/demo/form/simple': typeof webDemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/about': typeof webAboutRoute
  '/dashboard': typeof appAppDashboardRoute
  '/sinistres': typeof appAppSinistresRoute
  '/demo/i18n': typeof webDemoI18nRoute
  '/demo/prisma': typeof webDemoPrismaRoute
  '/demo/store': typeof webDemoStoreRoute
  '/demo/table': typeof webDemoTableRoute
  '/': typeof webWebIndexRoute
  '/demo/form/address': typeof webDemoFormAddressRoute
  '/demo/form/simple': typeof webDemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_app': typeof appAppRouteWithChildren
  '/(web)/_web': typeof webWebRouteWithChildren
  '/(web)/about': typeof webAboutRoute
  '/(app)/_app/dashboard': typeof appAppDashboardRoute
  '/(app)/_app/sinistres': typeof appAppSinistresRoute
  '/(web)/demo/i18n': typeof webDemoI18nRoute
  '/(web)/demo/prisma': typeof webDemoPrismaRoute
  '/(web)/demo/store': typeof webDemoStoreRoute
  '/(web)/demo/table': typeof webDemoTableRoute
  '/(web)/_web/': typeof webWebIndexRoute
  '/(web)/demo/form/address': typeof webDemoFormAddressRoute
  '/(web)/demo/form/simple': typeof webDemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/dashboard'
    | '/sinistres'
    | '/demo/i18n'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/table'
    | '/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/dashboard'
    | '/sinistres'
    | '/demo/i18n'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/table'
    | '/'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/(app)/_app'
    | '/(web)/_web'
    | '/(web)/about'
    | '/(app)/_app/dashboard'
    | '/(app)/_app/sinistres'
    | '/(web)/demo/i18n'
    | '/(web)/demo/prisma'
    | '/(web)/demo/store'
    | '/(web)/demo/table'
    | '/(web)/_web/'
    | '/(web)/demo/form/address'
    | '/(web)/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
  webWebRoute: typeof webWebRouteWithChildren
  webAboutRoute: typeof webAboutRoute
  webDemoI18nRoute: typeof webDemoI18nRoute
  webDemoPrismaRoute: typeof webDemoPrismaRoute
  webDemoStoreRoute: typeof webDemoStoreRoute
  webDemoTableRoute: typeof webDemoTableRoute
  webDemoFormAddressRoute: typeof webDemoFormAddressRoute
  webDemoFormSimpleRoute: typeof webDemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/_web': {
      id: '/(web)/_web'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof webWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/about': {
      id: '/(web)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof webAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/dashboard': {
      id: '/(app)/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appAppDashboardRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/sinistres': {
      id: '/(app)/_app/sinistres'
      path: '/sinistres'
      fullPath: '/sinistres'
      preLoaderRoute: typeof appAppSinistresRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(web)/_web/': {
      id: '/(web)/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof webWebIndexRouteImport
      parentRoute: typeof webWebRoute
    }
    '/(web)/demo/i18n': {
      id: '/(web)/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof webDemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/demo/prisma': {
      id: '/(web)/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof webDemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/demo/store': {
      id: '/(web)/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof webDemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/demo/table': {
      id: '/(web)/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof webDemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/demo/form/address': {
      id: '/(web)/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof webDemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(web)/demo/form/simple': {
      id: '/(web)/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof webDemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appAppRouteChildren {
  appAppDashboardRoute: typeof appAppDashboardRoute
  appAppSinistresRoute: typeof appAppSinistresRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppDashboardRoute: appAppDashboardRoute,
  appAppSinistresRoute: appAppSinistresRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface webWebRouteChildren {
  webWebIndexRoute: typeof webWebIndexRoute
}

const webWebRouteChildren: webWebRouteChildren = {
  webWebIndexRoute: webWebIndexRoute,
}

const webWebRouteWithChildren =
  webWebRoute._addFileChildren(webWebRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
  webWebRoute: webWebRouteWithChildren,
  webAboutRoute: webAboutRoute,
  webDemoI18nRoute: webDemoI18nRoute,
  webDemoPrismaRoute: webDemoPrismaRoute,
  webDemoStoreRoute: webDemoStoreRoute,
  webDemoTableRoute: webDemoTableRoute,
  webDemoFormAddressRoute: webDemoFormAddressRoute,
  webDemoFormSimpleRoute: webDemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
